export default {
	kind: "customsearch#search",
	url: {
		type: "application/json",
		template: "https://www.googleapis.com/customsearch/v1?q={searchTerms}&num={count?}&start={startIndex?}&lr={language?}&safe={safe?}&cx={cx?}&sort={sort?}&filter={filter?}&gl={gl?}&cr={cr?}&googlehost={googleHost?}&c2coff={disableCnTwTranslation?}&hq={hq?}&hl={hl?}&siteSearch={siteSearch?}&siteSearchFilter={siteSearchFilter?}&exactTerms={exactTerms?}&excludeTerms={excludeTerms?}&linkSite={linkSite?}&orTerms={orTerms?}&relatedSite={relatedSite?}&dateRestrict={dateRestrict?}&lowRange={lowRange?}&highRange={highRange?}&searchType={searchType}&fileType={fileType?}&rights={rights?}&imgSize={imgSize?}&imgType={imgType?}&imgColorType={imgColorType?}&imgDominantColor={imgDominantColor?}&alt=json",
	},
	queries: {
		request: [
			{
				title: "Google Custom Search - react developer",
				totalResults: "7",
				searchTerms: "react developer",
				count: 7,
				startIndex: 1,
				inputEncoding: "utf8",
				outputEncoding: "utf8",
				safe: "off",
				cx: "03908a5d59a5572b0",
			},
		],
	},
	context: {
		title: "Google",
	},
	searchInformation: {
		searchTime: 0.770585,
		formattedSearchTime: "0.77",
		totalResults: "7",
		formattedTotalResults: "7",
	},
	items: [
		{
			kind: "customsearch#result",
			title: "Network security configuration | Android Developers",
			htmlTitle: "Network security configuration | Android <b>Developers</b>",
			link: "https://www.google.com/appserve/mkt/p/ABMBUQPUZhnafMC1aUODWh1AM2pKdNfT-FdfzJnsjMXtl22sM5e7fvHvA6wt3OuUcfXuckgCdB3hbee3FRgwD4yt3bnktqSsXx5CDDRwLMyjaaLSX_540FO8pFhOpWVC27pD5P8Qqdz7",
			displayLink: "www.google.com",
			snippet: "Apr 1, 2021 ... Feature that allows app developers to customize network security settings in a safe configuration file.",
			htmlSnippet: "Apr 1, 2021 <b>...</b> Feature that allows app <b>developers</b> to customize network security settings in a safe configuration file.",
			cacheId: "hOONLxvMTwYJ",
			formattedUrl: "https://www.google.com/.../ABMBUQPUZhnafMC1aUODWh1AM2pKdNfT- FdfzJnsjMXtl22sM5e7fvHvA6wt3OuUcfXuckgCdB3hbee3FRgwD4yt3bnk...",
			htmlFormattedUrl: "https://www.google.com/.../ABMBUQPUZhnafMC1aUODWh1AM2pKdNfT- FdfzJnsjMXtl22sM5e7fvHvA6wt3OuUcfXuckgCdB3hbee3FRgwD4yt3bnk...",
			pagemap: {
				metatags: [
					{
						"og:image": "https://developer.android.com/images/cards/android-security_2x.png",
						"og:type": "website",
						"theme-color": "#3ddc84",
						"og:image:width": "1200",
						"twitter:card": "summary_large_image",
						"google-signin-client-id": "721724668570-nbkv1cfusk7kk4eni4pjvepaus73b13t.apps.googleusercontent.com",
						"og:site_name": "Android Developers",
						"og:title": "Network security configuration  |  Android Developers",
						"og:image:height": "675",
						"og:description": "Feature that allows app developers to customize network security settings in a safe configuration file.",
						viewport: "width=device-width, initial-scale=1",
						"og:locale": "en",
						"google-signin-scope": "profile email https://www.googleapis.com/auth/developerprofiles https://www.googleapis.com/auth/developerprofiles.award",
						"og:url": "https://developer.android.com/training/articles/security-config",
					},
				],
				cse_image: [
					{
						src: "https://developer.android.com/images/cards/android-security_2x.png",
					},
				],
			},
		},
		{
			kind: "customsearch#result",
			title: "Google Play In-App Review API | Android Developers",
			htmlTitle: "Google Play In-App Review API | Android <b>Developers</b>",
			link: "https://www.google.com/appserve/mkt/p/AD-FnEx1FLuH17Zl1VF43jWsfVgJpm225O4lLtOLbfzNZtkmjFeCsSeMJuTT7sGB_GJX-N-7-BPHubAPpDI07Wku3Tb0ikz-_F8LQWK_CQsf2jx2spUsrocVDJwz5h_xvh8BidXEpcQ47PEn7kc7yOcE5lqhb5F4Qw",
			displayLink: "www.google.com",
			snippet: "Jul 17, 2021 ... To protect user privacy and avoid API misuse, there are strict guidelines that your app should follow about when to request in-app reviews and ...",
			htmlSnippet: "Jul 17, 2021 <b>...</b> To protect user privacy and avoid API misuse, there are strict guidelines that your app should follow about when to request in-app reviews and&nbsp;...",
			cacheId: "d1_513TrA7MJ",
			formattedUrl: "https://www.google.com/.../AD- FnEx1FLuH17Zl1VF43jWsfVgJpm225O4lLtOLbfzNZtkmjFeCsSeMJuTT7...",
			htmlFormattedUrl: "https://www.google.com/.../AD- FnEx1FLuH17Zl1VF43jWsfVgJpm225O4lLtOLbfzNZtkmjFeCsSeMJuTT7...",
			pagemap: {
				cse_thumbnail: [
					{
						src: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTIiyuDULJELWS4EckDT_NkpCNM8Q6P_8ye5QbltHzulEvkPJbJPmpxmHzl",
						width: "299",
						height: "168",
					},
				],
				metatags: [
					{
						"og:image": "https://developer.android.com/images/social/android-developers.png",
						"og:type": "website",
						"theme-color": "#3ddc84",
						"og:image:width": "1200",
						"twitter:card": "summary_large_image",
						"google-signin-client-id": "721724668570-nbkv1cfusk7kk4eni4pjvepaus73b13t.apps.googleusercontent.com",
						"og:site_name": "Android Developers",
						"og:title": "Google Play In-App Review API  |  Android Developers",
						"og:image:height": "675",
						viewport: "width=device-width, initial-scale=1",
						"og:locale": "en",
						"google-signin-scope": "profile email https://www.googleapis.com/auth/developerprofiles https://www.googleapis.com/auth/developerprofiles.award",
						"og:url": "https://developer.android.com/guide/playcore/in-app-review",
					},
				],
				cse_image: [
					{
						src: "https://developer.android.com/images/social/android-developers.png",
					},
				],
			},
		},
		{
			kind: "customsearch#result",
			title: "Design - Material Design",
			htmlTitle: "Design - Material Design",
			link: "https://www.google.com/design/spec",
			displayLink: "www.google.com",
			snippet: "Developer docs and design guidelines for components now live in one place, separated by tabs. December 14, 2020. Material Design Award winners.",
			htmlSnippet: "<b>Developer</b> docs and design guidelines for components now live in one place, separated by tabs. December 14, 2020. Material Design Award winners.",
			cacheId: "k5Q76cxAbUUJ",
			formattedUrl: "https://www.google.com/design/spec",
			htmlFormattedUrl: "https://www.google.com/design/spec",
			pagemap: {
				cse_thumbnail: [
					{
						src: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQx4wuKCEX2h1q4dj_jwAMG86_el3Qy10Yi5dC41GI0EToT96_3MvVhomfx",
						width: "225",
						height: "225",
					},
				],
				metatags: [
					{
						"og:image": "https://material.io/static/assets/result.png",
						"twitter:title": "Material Design",
						"og:type": "article",
						"twitter:card": "summary_large_image",
						"theme-color": "#ffffff",
						"og:site_name": "Material Design",
						"twitter:url": "https://material.io",
						"og:title": "Material Design",
						"og:description": "Build beautiful, usable products faster. Material Design is an adaptable system—backed by open-source code—that helps teams build high quality digital experiences.",
						"twitter:image": "https://material.io/static/assets/result.png",
						viewport: "initial-scale=1, width=device-width",
						"twitter:description": "Build beautiful, usable products faster. Material Design is an adaptable system—backed by open-source code—that helps teams build high quality digital experiences.",
						"format-detection": "telephone=no",
					},
				],
				cse_image: [
					{
						src: "https://material.io/static/assets/result.png",
					},
				],
			},
		},
		{
			kind: "customsearch#result",
			title: "Newest Questions - Stack Overflow",
			htmlTitle: "Newest Questions - Stack Overflow",
			link: "http://www.google.com/appserve/mkt/p/AFnwnKVW8Ov2h0yFzGQYWDHZ4CxauYc72aE3poSobduKvleBuVT29fNVOEpb_D9ZMqqTUAAYnOnJQGgBL5Kv2h_2vFG_69di",
			displayLink: "www.google.com",
			snippet: "I am using https://www.npmjs.com/package/opengraph-react It says if the prop ... that are simple enough for any developer, yet robust enough to power the ...",
			htmlSnippet: "I am using https://www.npmjs.com/package/opengraph-<b>react</b> It says if the prop ... that are simple enough for any <b>developer</b>, yet robust enough to power the&nbsp;...",
			cacheId: "vGOvDTSq2k8J",
			formattedUrl: "www.google.com/.../ AFnwnKVW8Ov2h0yFzGQYWDHZ4CxauYc72aE3poSobduKvleBuVT29...",
			htmlFormattedUrl: "www.google.com/.../ AFnwnKVW8Ov2h0yFzGQYWDHZ4CxauYc72aE3poSobduKvleBuVT29...",
			pagemap: {
				cse_thumbnail: [
					{
						src: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQYl7zuT3cw_BBRAyhdQEbQuBgqdNHXKHIYKL8S8ly8x9L_XA9sdwSmiHs",
						width: "225",
						height: "225",
					},
				],
				metatags: [
					{
						"og:image": "https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon@2.png?v=73d79a89bded",
						"og:type": "website",
						"twitter:card": "summary",
						"twitter:title": "Newest Questions",
						"og:site_name": "Stack Overflow",
						"twitter:domain": "stackoverflow.com",
						viewport: "width=device-width, height=device-height, initial-scale=1.0, minimum-scale=1.0",
						"twitter:description": "Stack Overflow | The World’s Largest Online Community for Developers",
						"og:url": "https://stackoverflow.com/questions",
					},
				],
				cse_image: [
					{
						src: "https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon@2.png?v=73d79a89bded",
					},
				],
			},
		},
		{
			kind: "customsearch#result",
			title: "Try New Features with Google Chrome Beta - Google Chrome",
			htmlTitle: "Try New Features with Google Chrome Beta - Google Chrome",
			link: "https://www.google.com/intl/en_in/chrome/beta/",
			displayLink: "www.google.com",
			snippet: "Dev and Partners. Chromium · Chrome OS · Chrome Web Store · Chrome Experiments · Chrome Beta · Chrome Dev · Chrome Canary ...",
			htmlSnippet: "<b>Dev</b> and Partners. Chromium &middot; Chrome OS &middot; Chrome Web Store &middot; Chrome Experiments &middot; Chrome Beta &middot; Chrome <b>Dev</b> &middot; Chrome Canary&nbsp;...",
			cacheId: "N0oynY0_zk4J",
			formattedUrl: "https://www.google.com/intl/en_in/chrome/beta/",
			htmlFormattedUrl: "https://www.google.com/intl/en_in/chrome/beta/",
			pagemap: {
				cse_thumbnail: [
					{
						src: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQvOtm0e8_-deA1oQRJw635_OTCjem2WtW4etIEOQivYwJomfyH0uGXbQ",
						width: "80",
						height: "80",
					},
				],
				metatags: [
					{
						"msapplication-config": "/chrome/static/images/favicons/browserconfig.xml",
						"og:image": "https://www.google.com/chrome/static/images/beta/chrome-beta-logo.svg",
						"twitter:card": "summary_large_image",
						"twitter:title": "Try New Features with Google Chrome Beta - Google Chrome",
						"og:type": "website",
						"twitter:url": "https://www.google.com/intl/en_in/chrome/beta/",
						"og:title": "Try New Features with Google Chrome Beta - Google Chrome",
						"og:description": "Feeling adventurous? Preview upcoming Google Chrome features before they’re released and give us feedback to make Chrome a better browser.",
						"twitter:image": "https://www.google.com/chrome/static/images/beta/chrome-beta-logo.svg",
						viewport: "width=device-width, initial-scale=1",
						"twitter:description": "Feeling adventurous? Preview upcoming Google Chrome features before they’re released and give us feedback to make Chrome a better browser.",
						"og:locale": "en_IN",
						"og:url": "https://www.google.com/intl/en_in/chrome/beta/",
					},
				],
				cse_image: [
					{
						src: "https://www.google.com/chrome/static/images/beta/chrome-beta-logo.svg",
					},
				],
			},
		},
		{
			kind: "customsearch#result",
			title: "How To Fix TBS Crossfire Binding Issues (via Emergency Update ...",
			htmlTitle: "How To Fix TBS Crossfire Binding Issues (via Emergency Update ...",
			link: "https://www.google.com/sorry/index?continue=https://www.youtube.com/watch%3Fv%3DdCY5vvYv9gM&q=EgRC-UoyGNnNpI8GIhASbNWUco59lFEtbQ4fdxOWMgI-Yw",
			displayLink: "www.google.com",
			snippet: "Sep 6, 2020 ... AboutPressCopyrightContact usCreatorsAdvertiseDevelopersTermsPrivacyPolicy & SafetyHow YouTube worksTest new features. © 2022 Google LLC.",
			htmlSnippet: "Sep 6, 2020 <b>...</b> AboutPressCopyrightContact usCreatorsAdvertise<b>Developers</b>TermsPrivacyPolicy &amp; SafetyHow YouTube worksTest new features. © 2022 Google LLC.",
			cacheId: "ZM7wrIcPGp0J",
			formattedUrl: "https://www.google.com/sorry/index?continue=https://www...com/...",
			htmlFormattedUrl: "https://www.google.com/sorry/index?continue=https://www...com/...",
			pagemap: {
				cse_thumbnail: [
					{
						src: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQdz_2q5fdHvIf5UEVS7Vw5C7PxgUvLFEwthSp-F4pCcNGXDWJxBqZuVGA",
						width: "259",
						height: "194",
					},
				],
				imageobject: [
					{
						width: "480",
						url: "https://i.ytimg.com/vi/dCY5vvYv9gM/hqdefault.jpg",
						height: "360",
					},
				],
				person: [
					{
						name: "MatrixFPV",
						url: "http://www.youtube.com/channel/UCM7QTmLx-mkzxj1oCWUm5NA",
					},
				],
				metatags: [
					{
						"og:image": "https://i.ytimg.com/vi/dCY5vvYv9gM/hqdefault.jpg",
						"twitter:app:url:iphone": "vnd.youtube://www.youtube.com/watch?v=dCY5vvYv9gM&feature=applinks",
						"twitter:app:id:googleplay": "com.google.android.youtube",
						"theme-color": "rgba(255, 255, 255, 0.98)",
						"og:image:width": "480",
						"twitter:card": "player",
						"og:site_name": "YouTube",
						"twitter:url": "https://www.youtube.com/watch?v=dCY5vvYv9gM",
						"twitter:app:url:ipad": "vnd.youtube://www.youtube.com/watch?v=dCY5vvYv9gM&feature=applinks",
						"al:android:package": "com.google.android.youtube",
						"twitter:app:name:googleplay": "YouTube",
						title: "How To Fix TBS Crossfire Binding Issues (via Emergency Update Procedure)",
						"al:ios:url": "vnd.youtube://www.youtube.com/watch?v=dCY5vvYv9gM&feature=applinks",
						"twitter:app:id:iphone": "544007664",
						"og:description": "In this video I am going to show you how to fix a common binding issue with your Team Blacksheep (TBS) Crossfire to your receivers via emergency update - app...",
						"al:ios:app_store_id": "544007664",
						"twitter:image": "https://i.ytimg.com/vi/dCY5vvYv9gM/hqdefault.jpg",
						"twitter:player": "https://www.youtube.com/embed/dCY5vvYv9gM",
						"twitter:site": "@youtube",
						"og:video:type": "text/html",
						"og:video:height": "720",
						"og:video:url": "https://www.youtube.com/embed/dCY5vvYv9gM",
						"og:type": "video.other",
						"twitter:title": "How To Fix TBS Crossfire Binding Issues (via Emergency Update Procedure)",
						"al:ios:app_name": "YouTube",
						"og:title": "How To Fix TBS Crossfire Binding Issues (via Emergency Update Procedure)",
						"og:image:height": "360",
						"twitter:app:id:ipad": "544007664",
						"al:web:url": "http://www.youtube.com/watch?v=dCY5vvYv9gM&feature=applinks",
						"og:video:secure_url": "https://www.youtube.com/embed/dCY5vvYv9gM",
						"og:video:tag": "TBS",
						"og:video:width": "1280",
						"al:android:url": "vnd.youtube://www.youtube.com/watch?v=dCY5vvYv9gM&feature=applinks",
						"fb:app_id": "87741124305",
						"twitter:app:url:googleplay": "https://www.youtube.com/watch?v=dCY5vvYv9gM",
						"twitter:app:name:ipad": "YouTube",
						"twitter:description": "In this video I am going to show you how to fix a common binding issue with your Team Blacksheep (TBS) Crossfire to your receivers via emergency update - app...",
						"og:url": "https://www.youtube.com/watch?v=dCY5vvYv9gM",
						"twitter:player:width": "1280",
						"al:android:app_name": "YouTube",
						"twitter:app:name:iphone": "YouTube",
					},
				],
				videoobject: [
					{
						embedurl: "https://www.youtube.com/embed/dCY5vvYv9gM",
						playertype: "HTML5 Flash",
						isfamilyfriendly: "true",
						uploaddate: "2020-09-06",
						description: "In this video I am going to show you how to fix a common binding issue with your Team Blacksheep (TBS) Crossfire to your receivers via emergency update - app...",
						videoid: "dCY5vvYv9gM",
						url: "https://www.youtube.com/watch?v=dCY5vvYv9gM",
						duration: "PT4M54S",
						unlisted: "False",
						name: "How To Fix TBS Crossfire Binding Issues (via Emergency Update Procedure)",
						paid: "False",
						width: "1280",
						regionsallowed: "AD,AE,AF,AG,AI,AL,AM,AO,AQ,AR,AS,AT,AU,AW,AX,AZ,BA,BB,BD,BE,BF,BG,BH,BI,BJ,BL,BM,BN,BO,BQ,BR,BS,BT,BV,BW,BY,BZ,CA,CC,CD,CF,CG,CH,CI,CK,CL,CM,CN,CO,CR,CU,CV,CW,CX,CY,CZ,DE,DJ,DK,DM,DO,DZ,EC,EE,EG,EH...",
						genre: "Howto & Style",
						interactioncount: "18045",
						channelid: "UCM7QTmLx-mkzxj1oCWUm5NA",
						datepublished: "2020-09-06",
						thumbnailurl: "https://i.ytimg.com/vi/dCY5vvYv9gM/hqdefault.jpg",
						height: "720",
					},
				],
				cse_image: [
					{
						src: "https://i.ytimg.com/vi/dCY5vvYv9gM/hqdefault.jpg",
					},
				],
			},
		},
		{
			kind: "customsearch#result",
			title: "Opel key learning problem - YouTube",
			htmlTitle: "Opel key learning problem - YouTube",
			link: "https://www.google.com/sorry/index?continue=https://www.youtube.com/watch%3Fv%3DWM-rvKJYhg0&q=EgRC-Un1GM_NpI8GIhACCTIVAjapNAhbdH_sGMXYMgM-PmM",
			displayLink: "www.google.com",
			snippet: "Dec 9, 2015 ... Learn Live - Build your first Bicep template. Microsoft Developer. Microsoft Developer. •. 15K views Streamed 9 days ago ...",
			htmlSnippet: "Dec 9, 2015 <b>...</b> Learn Live - Build your first Bicep template. Microsoft <b>Developer</b>. Microsoft <b>Developer</b>. •. 15K views Streamed 9 days ago&nbsp;...",
			formattedUrl: "https://www.google.com/sorry/index?continue=https://www...q...",
			htmlFormattedUrl: "https://www.google.com/sorry/index?continue=https://www...q...",
			pagemap: {
				cse_thumbnail: [
					{
						src: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSKgSt5robnd9A75RCmHAamECB2oPlWB3PhHdU3EZMSvga79fwSys1DAg",
						width: "168",
						height: "94",
					},
				],
				imageobject: [
					{
						width: "480",
						url: "https://i.ytimg.com/vi/WM-rvKJYhg0/hqdefault.jpg",
						height: "360",
					},
				],
				person: [
					{
						name: "Mar Kow",
						url: "http://www.youtube.com/channel/UCCcLD46Y3yxuYb7oJh6TPyw",
					},
				],
				metatags: [
					{
						"og:image": "https://i.ytimg.com/vi/WM-rvKJYhg0/hqdefault.jpg",
						"twitter:app:url:iphone": "vnd.youtube://www.youtube.com/watch?v=WM-rvKJYhg0&feature=applinks",
						"twitter:app:id:googleplay": "com.google.android.youtube",
						"theme-color": "rgba(255,255,255,0.98)",
						"og:image:width": "480",
						"twitter:card": "player",
						"og:site_name": "YouTube",
						"twitter:url": "https://www.youtube.com/watch?v=WM-rvKJYhg0",
						"twitter:app:url:ipad": "vnd.youtube://www.youtube.com/watch?v=WM-rvKJYhg0&feature=applinks",
						"al:android:package": "com.google.android.youtube",
						"twitter:app:name:googleplay": "YouTube",
						title: "Opel key learning problem",
						"al:ios:url": "vnd.youtube://www.youtube.com/watch?v=WM-rvKJYhg0&feature=applinks",
						"twitter:app:id:iphone": "544007664",
						"og:description": "Clips are short since any other representatives of the Bulgarian company report for removal.If you decide to buy equipment with them, buy gradually and test,...",
						"al:ios:app_store_id": "544007664",
						"twitter:image": "https://i.ytimg.com/vi/WM-rvKJYhg0/hqdefault.jpg",
						"twitter:player": "https://www.youtube.com/embed/WM-rvKJYhg0",
						"twitter:player:height": "360",
						"twitter:site": "@youtube",
						"og:video:type": "text/html",
						"og:video:height": "360",
						"og:video:url": "https://www.youtube.com/embed/WM-rvKJYhg0",
						"og:type": "video.other",
						"twitter:title": "Opel key learning problem",
						"al:ios:app_name": "YouTube",
						"og:title": "Opel key learning problem",
						"og:image:height": "360",
						"twitter:app:id:ipad": "544007664",
						"al:web:url": "http://www.youtube.com/watch?v=WM-rvKJYhg0&feature=applinks",
						"og:video:secure_url": "https://www.youtube.com/embed/WM-rvKJYhg0",
						"og:video:width": "640",
						"al:android:url": "vnd.youtube://www.youtube.com/watch?v=WM-rvKJYhg0&feature=applinks",
						"fb:app_id": "87741124305",
						"twitter:app:url:googleplay": "https://www.youtube.com/watch?v=WM-rvKJYhg0",
						"twitter:app:name:ipad": "YouTube",
						"twitter:description": "Clips are short since any other representatives of the Bulgarian company report for removal.If you decide to buy equipment with them, buy gradually and test,...",
						"og:url": "https://www.youtube.com/watch?v=WM-rvKJYhg0",
						"twitter:player:width": "640",
						"al:android:app_name": "YouTube",
						"twitter:app:name:iphone": "YouTube",
					},
				],
				videoobject: [
					{
						embedurl: "https://www.youtube.com/embed/WM-rvKJYhg0",
						playertype: "HTML5 Flash",
						isfamilyfriendly: "true",
						uploaddate: "2015-12-09",
						description: "Clips are short since any other representatives of the Bulgarian company report for removal.If you decide to buy equipment with them, buy gradually and test,...",
						videoid: "WM-rvKJYhg0",
						url: "https://www.youtube.com/watch?v=WM-rvKJYhg0",
						duration: "PT0M36S",
						unlisted: "False",
						name: "Opel key learning problem",
						paid: "False",
						width: "640",
						regionsallowed: "AD,AE,AF,AG,AI,AL,AM,AO,AQ,AR,AS,AT,AU,AW,AX,AZ,BA,BB,BD,BE,BF,BG,BH,BI,BJ,BL,BM,BN,BO,BQ,BR,BS,BT,BV,BW,BY,BZ,CA,CC,CD,CF,CG,CH,CI,CK,CL,CM,CN,CO,CR,CU,CV,CW,CX,CY,CZ,DE,DJ,DK,DM,DO,DZ,EC,EE,EG,EH...",
						genre: "People & Blogs",
						interactioncount: "164",
						channelid: "UCCcLD46Y3yxuYb7oJh6TPyw",
						datepublished: "2015-12-09",
						thumbnailurl: "https://i.ytimg.com/vi/WM-rvKJYhg0/hqdefault.jpg",
						height: "360",
					},
				],
				cse_image: [
					{
						src: "https://i.ytimg.com/vi/2PGnYjbYuUo/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLAG-mlMYI5zOx5N5_NI5Hzo8hSjIg",
					},
				],
			},
		},
	],
};
